# Generated by Django 5.1.6 on 2025-03-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
        ('stores', '0003_alter_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stores',
            field=models.ManyToManyField(related_name='orders', to='stores.store'),
        ),
    ]
