# Generated by Django 5.1.6 on 2025-03-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
    ]
