# Generated by Django 5.1.6 on 2025-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_stores'),
        ('stores', '0003_alter_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='orders', to='stores.store'),
        ),
    ]
